<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="aruco_robot">

  <xacro:property name="base_x" value="1.0"/>
  <xacro:property name="base_y" value="1.0"/>
  <xacro:property name="base_z" value="0.05"/>
  <xacro:property name="link_xy" value="0.05"/>
  <xacro:property name="link_z" value="1.5"/>
  <xacro:property name="tcp_x" value="0.1"/>
  <xacro:property name="tcp_y" value="0.1"/>
  <xacro:property name="tcp_z" value="0.1"/>

  <material name="blue">
    <color rgba="0.0 0.5 1.0 1.0"/>
  </material>

  <material name="red">
    <color rgba="1.0 0.5 0.0 1.0"/>
  </material>


  <link name="base">
    <!-- base -->
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="${base_x} ${base_y} ${base_z}"/>
      </geometry>
      <material name="blue"/>

    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="${base_x} ${base_y} ${base_z}"/>
      </geometry>

    </collision>

    <inertial>
      <mass value="5"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>

    <!-- link -->
    <visual>
      <origin xyz="${base_x/2} 0.0 ${link_z/2}" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="${link_xy} ${link_xy} ${link_z}"/>
      </geometry>
      <material name="blue"/>

    </visual>

    <collision>
      <origin xyz="${base_x/2} 0.0 ${link_z/2}" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="${link_xy} ${link_xy} ${link_z}"/>
      </geometry>

    </collision>

  </link>

  <gazebo reference="base">
    <material>aruco/material</material>
  </gazebo>

  <link name="tcp">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="${tcp_x} ${tcp_z} ${tcp_y}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="${tcp_x} ${tcp_z} ${tcp_y}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.005" iyz="0.0" izz="0.005"/>
    </inertial>
  </link>

  <gazebo reference="tcp">
    <material>Gazebo/Red</material>
  </gazebo>

  <joint name="joint_base_tcp" type="continuous">
    <parent link="base"/>
    <child link="tcp"/>
    <axis xyz="1 0 0"/>
    <origin xyz="0.0 0.0 ${link_z}" rpy="0 0 0"/>
  </joint>
  

</robot>